### ISSUE TITLE
opendingux: rg350(m): gmenu2x can't read battery charge status

### ISSUE THREAD

**Issue by jezze** [OpenDingux/buildroot#25] opened 2020-10-09 18:52 UTC
There are at least two issues.

The path to the power supply is different from how it was on the GCW Zero. It used to be /sys/class/power_supply/act8600-charger but since that doesnt exist we could use /sys/class/power_supply/usb-charger instead for the rg350m. This needs to be changed in /usr/share/gmenu2x/gmenu2x.conf.

The path to the battery is the same as it was /sys/class/power_supply/jz-battery but on the gcw there are two files called status and capacity in that directory and those do not exist on the rg350m. In gmenu2x you could chose to remove the check for those because I don't think they are strictly necessary to figure out the charge level of the battery. Right now because these files do not exist, no charge level calculation is taking place.

**Comment by acarteron** [comment] 2020-10-18 20:49
gmenu2x can handle battery status using voltage_max_design  voltage_min_design  voltage_now files.
The issue is that voltage_now might contains a wrong value that never increase or decrease with battery charge.
But when an application that not use joystick (e.g. Terminal) is used, the value increase or decrease with battery charge even if it does not correspond to real battery voltage.

In gmenu2x:
```
rg350m:~ $ cat /sys/class/power_supply/jz-battery/voltage_now 
2694000
```
Terminal application started:
```
rg350m:~ $ cat /sys/class/power_supply/jz-battery/voltage_now 
5170000
```

**Comment by pcercuei** [comment] 2020-11-22 10:40
I think it's fixed now in the latest nightly, correct?

**Closed as completed** 2021-01-19 17:35 UTC
